app:
  name: App Developer
  port: 8686
  debug: true
  version: v1.0.0
  migrationsPath: pkg/migrates # path folder containing migration files
  logPath: ./app.log # path file to log application
  i18nPath: /home/nexsoft/TUTORIAL/go/go-boilerplate/pkg/i18n # path folder containing i18n files

database:
  host: localhost
  port: 5432
  user: postgres
  password: mysecretpassword
  name: normal-db
  printQuery: 2 # 1 -> not print, 2 -> print error, 3 -> print warn, 4 -> print info
  connMaxLifetime: 30 # in minutes
  connMaxIdleTime: 10 # in minutes
  maxOpenConns: 100
  maxIdleConns: 10

