app:
  name: App Developer
  port: 8686
  debug: true
  version: v1.0.0
  migrationsPath: pkg/migrates # path folder containing migration files
  logPath: ./app.log # path file to log application

database:
  host: localhost
  port: 5432
  user: postgres
  password: mysecretpassword
  name: mydatabase
  printQuery: 2 # 1 -> not print, 2 -> print error, 3 -> print warn, 4 -> print info
