package domain

import "database/sql"

type Product struct {
	CompanyID                string          `gorm:"primaryKey;column:companyID"`
	ProductCode              string          `gorm:"primaryKey;column:productCode"`
	PrincipalProductCode     string          `gorm:"column:principalProductCode"`
	ProductName              sql.NullString  `gorm:"column:productName"`
	ProductPackaging         sql.NullString  `gorm:"column:productPackaging"`
	ProductDescription       sql.NullString  `gorm:"column:productDescription"`
	DivisionID               sql.NullString  `gorm:"column:divisionID"`
	PgLevel1ID               sql.NullString  `gorm:"column:pgLevel1ID"`
	PgLevel2ID               sql.NullString  `gorm:"column:pgLevel2ID"`
	PgLevel3ID               sql.NullString  `gorm:"column:pgLevel3ID"`
	VendorID                 sql.NullString  `gorm:"column:vendorID"`
	BrandID                  sql.NullString  `gorm:"column:brandID"`
	ProductCategoryID        sql.NullString  `gorm:"column:productCategoryID"`
	Uom1                     sql.NullString  `gorm:"column:uom1"`
	Bla                      sql.NullInt32   `gorm:"column:bla"`
	Uom2                     sql.NullString  `gorm:"column:uom2"`
	Uom3                     sql.NullString  `gorm:"column:uom3"`
	Uom4                     sql.NullString  `gorm:"column:uom4"`
	Conversion1to4           sql.NullInt32   `gorm:"column:conversion1to4"`
	Conversion2to4           sql.NullInt32   `gorm:"column:conversion2to4"`
	Conversion3to4           sql.NullInt32   `gorm:"column:conversion3to4"`
	MarketLaunchDate         sql.NullTime    `gorm:"column:marketLaunchDate"`
	WeightPerUnit            sql.NullFloat64 `gorm:"column:weightPerUnit"`
	VolumePerUnit            sql.NullFloat64 `gorm:"column:volumePerUnit"`
	CaseWidth                sql.NullFloat64 `gorm:"column:caseWidth"`
	CaseHeight               sql.NullFloat64 `gorm:"column:caseHeight"`
	CaseDepth                sql.NullFloat64 `gorm:"column:caseDepth"`
	CaseWeight               sql.NullFloat64 `gorm:"column:caseWeight"`
	BarcodeListForUom1       sql.NullString  `gorm:"column:barcodeListForUom1"`
	BarcodeListForUom2       sql.NullString  `gorm:"column:barcodeListForUom2"`
	BarcodeListForUom3       sql.NullString  `gorm:"column:barcodeListForUom3"`
	BarcodeListForUom4       sql.NullString  `gorm:"column:barcodeListForUom4"`
	IsProductWithVarian      sql.NullString  `gorm:"column:isProductWithVarian"`
	IsProductWithBatch       sql.NullString  `gorm:"column:isProductWithBatch"`
	IsInventoryItem          sql.NullString  `gorm:"column:isInventoryItem"`
	IsFreeGoodItem           sql.NullString  `gorm:"column:isFreeGoodItem"`
	IsEmbalaceItem           sql.NullString  `gorm:"column:isEmbalaceItem"`
	IsTax1Applied            sql.NullString  `gorm:"column:isTax1Applied"`
	IsTax2Applied            sql.NullString  `gorm:"column:isTax2Applied"`
	IsTax3Applied            sql.NullString  `gorm:"column:isTax3Applied"`
	IsTaxSubsidized          sql.NullString  `gorm:"column:isTaxSubsidized"`
	ProductClass             sql.NullInt16   `gorm:"column:productClass"`
	ProductStatus            sql.NullString  `gorm:"column:productStatus"`
	ReportColumnHeader1      sql.NullString  `gorm:"column:reportColumnHeader1"`
	ReportColumnHeader2      sql.NullString  `gorm:"column:reportColumnHeader2"`
	ProductSortSequence      sql.NullInt32   `gorm:"column:productSortSequence"`
	AdditionalMargin         sql.NullFloat64 `gorm:"column:additionalMargin"`
	MinQtyPerLines           sql.NullInt16   `gorm:"column:minQtyPerLines"`
	IsAllocatedItem          sql.NullString  `gorm:"column:isAllocatedItem"`
	IsNoPurchaseReturn       sql.NullString  `gorm:"column:isNoPurchaseReturn"`
	IsNoSalesReturn          sql.NullString  `gorm:"column:isNoSalesReturn"`
	AllowSellUnderCost       sql.NullString  `gorm:"column:allowSellUnderCost"`
	AllowEditPrice           sql.NullString  `gorm:"column:allowEditPrice"`
	IsNoRegularDiscount      sql.NullString  `gorm:"column:isNoRegularDiscount"`
	MinStockLevel            sql.NullInt16   `gorm:"column:minStockLevel"`
	MaxStockLevel            sql.NullInt16   `gorm:"column:maxStockLevel"`
	BufferStockLevel         sql.NullFloat64 `gorm:"column:bufferStockLevel"`
	WeekRPPOB                sql.NullInt16   `gorm:"column:weekRPPOB"`
	SellingPriceUom1         sql.NullFloat64 `gorm:"column:sellingPriceUom1"`
	BuyingPriceUom1          sql.NullFloat64 `gorm:"column:buyingPriceUom1"`
	ProductPoint             sql.NullInt16   `gorm:"column:productPoint"`
	ProductCreated           sql.NullTime    `gorm:"column:productCreated"`
	ProductModified          sql.NullTime    `gorm:"column:productModified"`
	ProductModifiedBy        sql.NullString  `gorm:"column:productModifiedBy"`
	ProductImageFileName1    sql.NullString  `gorm:"column:productImageFileName1"`
	ProductImageFileName2    sql.NullString  `gorm:"column:productImageFileName2"`
	ProductImageFileName3    sql.NullString  `gorm:"column:productImageFileName3"`
	ProductImageFileName4    sql.NullString  `gorm:"column:productImageFileName4"`
	ProductImageFileName5    sql.NullString  `gorm:"column:productImageFileName5"`
	FarmalkesID              sql.NullString  `gorm:"column:farmalkesID"`
	FarmalkesDesc            sql.NullString  `gorm:"column:farmalkesDesc"`
	MinSellingPrice          sql.NullFloat64 `gorm:"column:minSellingPrice"`
	MaxSellingPrice          sql.NullFloat64 `gorm:"column:maxSellingPrice"`
	IsHideInvoice            sql.NullString  `gorm:"column:isHideInvoice"`
	InsentiveCaseHelper      sql.NullInt32   `gorm:"column:insentiveCaseHelper"`
	InsentiveCaseDriver      sql.NullInt32   `gorm:"column:insentiveCaseDriver"`
	ProductActivation        sql.NullString  `gorm:"column:productActivation"`
	ParentCode               sql.NullString  `gorm:"column:parentCode"`
	ShortCode                sql.NullString  `gorm:"column:shortCode"`
	PriceUOM                 sql.NullInt16   `gorm:"column:priceUOM"`
	NormalStock              sql.NullInt32   `gorm:"column:normalStock"`
	GromartProductCode       sql.NullString  `gorm:"column:gromartProductCode"`
	PricePerKilo             sql.NullFloat64 `gorm:"column:pricePerKilo"`
	PriceBasedOnKilo         sql.NullString  `gorm:"column:priceBasedOnKilo"`
	ProductCodeBottle        sql.NullString  `gorm:"column:productCodeBottle"`
	ProductCodeCrate         sql.NullString  `gorm:"column:productCodeCrate"`
	ProductName2             sql.NullString  `gorm:"column:productName2"`
	ProductPackaging2        sql.NullString  `gorm:"column:productPackaging2"`
	GrossMargin              sql.NullFloat64 `gorm:"column:grossMargin"`
	NexchiefRatio            sql.NullFloat64 `gorm:"column:nexchiefRatio"`
	DryWeightPerUnit         sql.NullFloat64 `gorm:"column:dryWeightPerUnit"`
	GlossWeightPerUnit       sql.NullFloat64 `gorm:"column:glossWeightPerUnit"`
	IsAssemblyItem           sql.NullString  `gorm:"column:isAssemblyItem"`
	PgLevel4ID               sql.NullString  `gorm:"column:pgLevel4ID"`
	PgLevel5ID               sql.NullString  `gorm:"column:pgLevel5ID"`
	PgLevel6ID               sql.NullString  `gorm:"column:pgLevel6ID"`
	Keyaccount1              sql.NullString  `gorm:"column:keyaccount1"`
	Keyaccount2              sql.NullString  `gorm:"column:keyaccount2"`
	Keyaccount3              sql.NullString  `gorm:"column:keyaccount3"`
	NetWeightPerCases        sql.NullFloat64 `gorm:"column:netWeightPerCases"`
	IsConsignmentItem        sql.NullString  `gorm:"column:isConsignmentItem"`
	SyncDate                 sql.NullTime    `gorm:"column:syncDate"`
	CompanyIDJB              sql.NullString  `gorm:"column:companyIDJB"`
	DivisionIDJB             sql.NullString  `gorm:"column:divisionIDJB"`
	NieProductCode           sql.NullString  `gorm:"column:nieProductCode"`
	NieExpiredDate           sql.NullTime    `gorm:"column:nieExpiredDate"`
	SendToCompleteDate       sql.NullTime    `gorm:"column:sendToCompleteDate"`
	IsSyncToNexcore          sql.NullTime    `gorm:"column:isSyncToNexcore"`
	Uom1Nexchief             sql.NullString  `gorm:"column:uom1Nexchief"`
	Uom2Nexchief             sql.NullString  `gorm:"column:uom2Nexchief"`
	Uom3Nexchief             sql.NullString  `gorm:"column:uom3Nexchief"`
	Uom4Nexchief             sql.NullString  `gorm:"column:uom4Nexchief"`
	Conversion1to4Nexchief   sql.NullInt32   `gorm:"column:conversion1to4Nexchief"`
	Conversion2to4Nexchief   sql.NullInt32   `gorm:"column:conversion2to4Nexchief"`
	Conversion3to4Nexchief   sql.NullInt32   `gorm:"column:conversion3to4Nexchief"`
	QtyConvert               sql.NullInt32   `gorm:"column:qtyConvert"`
	IsProductChild           sql.NullString  `gorm:"column:isProductChild"`
	DescriptionCauseOfFailed sql.NullString  `gorm:"column:descriptionCauseOfFailed"`
	TransactionCode          sql.NullString  `gorm:"column:transactionCode"`
	SellingPriceUom2         sql.NullFloat64 `gorm:"column:sellingPriceUom2"`
	SellingPriceUom3         sql.NullFloat64 `gorm:"column:sellingPriceUom3"`
	SellingPriceUom4         sql.NullFloat64 `gorm:"column:sellingPriceUom4"`
	BuyingPriceUom2          sql.NullFloat64 `gorm:"column:buyingPriceUom2"`
	BuyingPriceUom3          sql.NullFloat64 `gorm:"column:buyingPriceUom3"`
	BuyingPriceUom4          sql.NullFloat64 `gorm:"column:buyingPriceUom4"`
}

func (Product) TableName() string {
	return "product"
}
